version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)5s - %(name)10s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  main:
    level: DEBUG
    handlers: [console]
    propagate: no
  schema:
    level: DEBUG
    handlers: [console]
    propagate: no
  salesforce:
    level: DEBUG
    handlers: [console]
    propagate: no
  dbdriver:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]